/*
 * Copyright Public Record Office Victoria 2018
 * Licensed under the CC-BY license http://creativecommons.org/licenses/by/3.0/au/
 * Author Andrew Waugh
 * Version 1.0 February 2018
 */
package VERSCommon;

import org.xml.sax.Attributes;
import org.xml.sax.SAXException;

/**
 * This interface represents the consumer of events generated by an XMLParser
 */
public interface XMLConsumer {

    /**
     * Callback when the start of a new element is found
     *
     * @param elementPath the path of qualified element names from the root of
     * the document tree
     * @param attributes collection of attributes associated with this element
     * @return what to do with the value of the element. If null, ignore the
     * value
     * @throws SAXException if processing of the document needs to be aborted
     */
    HandleElement startElement(String elementPath, Attributes attributes) throws SAXException;

    /**
     * Callback when the end of an element is found
     *
     * @param elementPath the path of qualified element names from the root of
     * the document tree
     * @param value the value, if instructed to collect it
     * @param element the value of the element (including tag) if it was being captured
     * @throws SAXException if processing of the document needs to be aborted
     */
    void endElement(String elementPath, String value, String element) throws SAXException;
}
